---

 - name: Install some packages
   action: apt name={{ item }} state=present
   with_items: "{{ pkg }}"

 - name: adding jenkins key to system
   apt_key: 
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present   

 - name: adding jenkins repo to sourced.list     
   apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list

 - name: doing update
   apt:
     update_cache: yes

 - name: install jenkins
   action: apt name=jenkins state=present
   notify: check jenkins status

 - name: debugging
   debug:
      var: myresult
  

     